version: "3"
services:
  db:
    image: mysql
    ports: 
      - "3306:3306"
      - "2020:22" 
    env_file:
      -  env/mysql-dev.env
    volumes:
      - ./db/data:/var/lib/mysql:rw
    restart: always
    networks:
      - back_end
  app:
    container_name: sns
    build:
      dockerfile: ./dockerfiles/Dockerfile-dev
      context: .
    env_file:
      - env/datasource-dev.env
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - back_end

networks:
  back_end: